workspace: "exp/aam"
trial_path: "data/vox1_clean.txt"
train_csv: "data/train.csv"
noise_csv: "data/noise.csv"
sample_rate: 16000
second: 2.5
batch_size: 192
num_workers: 64
save_top_k: 30
checkpoint_path: None
keep_loss_weight: False
spk_utt: 100
num_per_speaker: 1
trainer:
        max_epochs: 50
        gpus: 3
        accelerator: dp
        check_val_every_n_epoch: 1
feature: 
        name: "Mel_Spectrogram"
        coef: 0.97
        n_fft: 512
        win_length: 400
        hop: 160
        n_mels: 64
backbone: 
        name: "resnet34"
        embedding_dim: 256
        num_channels: [1, 32, 64, 128, 256]
        n_mels: 64
        pooling_type: "TSP"
loss:
        name: "amsoftmax"
        embedding_dim: 256
        margin: 0.2
        scale: 30
optim:
        name: "Adam"
        lr: 0.01
        weight_decay: 0.0
warmup_step: 500
schedule:
        name: "StepLR"
        gamma: 0.1
        step_size: 10
